# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build and Test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      WAPPSTO_ADMIN_USERNAME : ${{ secrets.WAPPSTO_ADMIN_USERNAME }}
      WAPPSTO_ADMIN_PASSWORD :  ${{ secrets.WAPPSTO_ADMIN_PASSWORD }}
      TESTPROJECT_DEV_TOKEN : ${{ secrets.TESTPROJECT_DEV_TOKEN }}
      WAPPSTO_API_ROOT : "https://qa.wappsto.com/services/2.0"
      WAPPSTO_APP_URL : "https://qa.wappsto.com/"
      WAPPSTO_ADMIN_PANEL_URL : "https://admin.qa.wappsto.com/"
      WAPPSTO_TEST_NETWORK : ${{ secrets.WAPPSTO_TEST_NETWORK }}
      WAPPSTO_DEVELOPER_USERNAME : ${{ secrets.APPSTO_DEVELOPER_USERNAME }}
      WAPPSTO_DEVELOPER_PASSWORD : ${{ secrets.WAPPSTO_DEVELOPER_PASSWORD }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.0
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: '11'
          # Java distribution. See the list of supported distributions in README file
          distribution: 'adopt'

      - name: Install TestProject SDK
        run: mvn install:install-file -Dfile=external-dep/TestProject_SDK_0.65.0.jar -DgroupId=io.testproject -DartifactId=java-sdk -Dversion=0.65.0 -Dpackaging=jar

      - name: Build and Run Tests with Surefire
        run: mvn test --batch-mode --fail-at-end
      
      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1
      
      
